/**
 *
 *  CameraProcess.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "CameraProcess.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::veda4;

const std::string CameraProcess::Cols::_id = "id";
const std::string CameraProcess::Cols::_camera_id = "camera_id";
const std::string CameraProcess::Cols::_process_name = "process_name";
const std::string CameraProcess::primaryKeyName = "id";
const bool CameraProcess::hasPrimaryKey = true;
const std::string CameraProcess::tableName = "camera_process";

const std::vector<typename CameraProcess::MetaData> CameraProcess::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"camera_id","int64_t","bigint",8,0,0,0},
{"process_name","std::string","enum('process1','process2','process3')",0,0,0,0}
};
const std::string &CameraProcess::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
CameraProcess::CameraProcess(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["camera_id"].isNull())
        {
            cameraId_=std::make_shared<int64_t>(r["camera_id"].as<int64_t>());
        }
        if(!r["process_name"].isNull())
        {
            processName_=std::make_shared<std::string>(r["process_name"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 3 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            cameraId_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            processName_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

CameraProcess::CameraProcess(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            cameraId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            processName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

CameraProcess::CameraProcess(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("camera_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["camera_id"].isNull())
        {
            cameraId_=std::make_shared<int64_t>((int64_t)pJson["camera_id"].asInt64());
        }
    }
    if(pJson.isMember("process_name"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["process_name"].isNull())
        {
            processName_=std::make_shared<std::string>(pJson["process_name"].asString());
        }
    }
}

void CameraProcess::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 3)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            cameraId_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            processName_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
}

void CameraProcess::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("camera_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["camera_id"].isNull())
        {
            cameraId_=std::make_shared<int64_t>((int64_t)pJson["camera_id"].asInt64());
        }
    }
    if(pJson.isMember("process_name"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["process_name"].isNull())
        {
            processName_=std::make_shared<std::string>(pJson["process_name"].asString());
        }
    }
}

const int64_t &CameraProcess::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &CameraProcess::getId() const noexcept
{
    return id_;
}
void CameraProcess::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}
const typename CameraProcess::PrimaryKeyType & CameraProcess::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int64_t &CameraProcess::getValueOfCameraId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(cameraId_)
        return *cameraId_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &CameraProcess::getCameraId() const noexcept
{
    return cameraId_;
}
void CameraProcess::setCameraId(const int64_t &pCameraId) noexcept
{
    cameraId_ = std::make_shared<int64_t>(pCameraId);
    dirtyFlag_[1] = true;
}
void CameraProcess::setCameraIdToNull() noexcept
{
    cameraId_.reset();
    dirtyFlag_[1] = true;
}

const std::string &CameraProcess::getValueOfProcessName() const noexcept
{
    static const std::string defaultValue = std::string();
    if(processName_)
        return *processName_;
    return defaultValue;
}
const std::shared_ptr<std::string> &CameraProcess::getProcessName() const noexcept
{
    return processName_;
}
void CameraProcess::setProcessName(const std::string &pProcessName) noexcept
{
    processName_ = std::make_shared<std::string>(pProcessName);
    dirtyFlag_[2] = true;
}
void CameraProcess::setProcessName(std::string &&pProcessName) noexcept
{
    processName_ = std::make_shared<std::string>(std::move(pProcessName));
    dirtyFlag_[2] = true;
}
void CameraProcess::setProcessNameToNull() noexcept
{
    processName_.reset();
    dirtyFlag_[2] = true;
}

void CameraProcess::updateId(const uint64_t id)
{
    id_ = std::make_shared<int64_t>(static_cast<int64_t>(id));
}

const std::vector<std::string> &CameraProcess::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "camera_id",
        "process_name"
    };
    return inCols;
}

void CameraProcess::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCameraId())
        {
            binder << getValueOfCameraId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProcessName())
        {
            binder << getValueOfProcessName();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> CameraProcess::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    return ret;
}

void CameraProcess::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getCameraId())
        {
            binder << getValueOfCameraId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getProcessName())
        {
            binder << getValueOfProcessName();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value CameraProcess::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCameraId())
    {
        ret["camera_id"]=(Json::Int64)getValueOfCameraId();
    }
    else
    {
        ret["camera_id"]=Json::Value();
    }
    if(getProcessName())
    {
        ret["process_name"]=getValueOfProcessName();
    }
    else
    {
        ret["process_name"]=Json::Value();
    }
    return ret;
}

Json::Value CameraProcess::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 3)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getCameraId())
            {
                ret[pMasqueradingVector[1]]=(Json::Int64)getValueOfCameraId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getProcessName())
            {
                ret[pMasqueradingVector[2]]=getValueOfProcessName();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getCameraId())
    {
        ret["camera_id"]=(Json::Int64)getValueOfCameraId();
    }
    else
    {
        ret["camera_id"]=Json::Value();
    }
    if(getProcessName())
    {
        ret["process_name"]=getValueOfProcessName();
    }
    else
    {
        ret["process_name"]=Json::Value();
    }
    return ret;
}

bool CameraProcess::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("camera_id"))
    {
        if(!validJsonOfField(1, "camera_id", pJson["camera_id"], err, true))
            return false;
    }
    if(pJson.isMember("process_name"))
    {
        if(!validJsonOfField(2, "process_name", pJson["process_name"], err, true))
            return false;
    }
    return true;
}
bool CameraProcess::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                       const std::vector<std::string> &pMasqueradingVector,
                                                       std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CameraProcess::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("camera_id"))
    {
        if(!validJsonOfField(1, "camera_id", pJson["camera_id"], err, false))
            return false;
    }
    if(pJson.isMember("process_name"))
    {
        if(!validJsonOfField(2, "process_name", pJson["process_name"], err, false))
            return false;
    }
    return true;
}
bool CameraProcess::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                     const std::vector<std::string> &pMasqueradingVector,
                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 3)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool CameraProcess::validJsonOfField(size_t index,
                                     const std::string &fieldName,
                                     const Json::Value &pJson,
                                     std::string &err,
                                     bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
